language: r
cache: packages

r_github_packages:
  - jimhester/covr

r_check_args: "--as-cran --run-dontrun"

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev libprotoc-dev valgrind
  - sudo add-apt-repository -y ppa:jeroen/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

compiler:
  - clang

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: KudAMnqi7D6dy1BruMF9tkT2PTUXa8VSuQo8ECk5M6gz6L7o6tEmzPgrzqLC9xzgc4mm80opMMdNGShTHZZdd1oWw9yIOFZpQ10O/kaLyb1LgFwV01yZP1dt9ZAxRvfm9Ur2wl8XS+cRr6PR7iJX733iBhQ+qUGDTltFm/O2q8U=
